repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0  # Verifique a versão mais recente em: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args: ["--config=./.tflint.hcl"]
      - id: terraform_docs
        args: ["--args=--sort-by-required"]
